Python 3.3.5rc2 (v3.3.5rc2:ca5635efe090, Mar  2 2014, 14:20:24) [MSC v.1600 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 
>>> run tests()
SyntaxError: invalid syntax
>>> run_tests()
Trying:
    bobs_change(80)
Expecting:
    30
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 17, in __main__
Failed example:
    bobs_change(80)
Expected:
    30
Got nothing
Trying:
    bobs_change(132)
Expecting:
    82
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 19, in __main__
Failed example:
    bobs_change(132)
Expected:
    82
Got nothing
Trying:
    bobs_change(50)
Expecting:
    0
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 21, in __main__
Failed example:
    bobs_change(50)
Expected:
    0
Got nothing
Trying:
    bobs_change(40)
Expecting:
    Sorry Bob, you don't have enough
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 23, in __main__
Failed example:
    bobs_change(40)
Expected:
    Sorry Bob, you don't have enough
Got:
    sorry not enough
2 items had no tests:
    __main__.bobs_change
    __main__.run_tests
**********************************************************************
1 items had failures:
   4 of   4 in __main__
4 tests in 3 items.
0 passed and 4 failed.
***Test Failed*** 4 failures.
>>> ================================ RESTART ================================
>>> 
>>> run_tests()
Trying:
    bobs_change(80)
Expecting:
    30
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 17, in __main__
Failed example:
    bobs_change(80)
Expected:
    30
Got nothing
Trying:
    bobs_change(132)
Expecting:
    82
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 19, in __main__
Failed example:
    bobs_change(132)
Expected:
    82
Got nothing
Trying:
    bobs_change(50)
Expecting:
    0
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 21, in __main__
Failed example:
    bobs_change(50)
Expected:
    0
Got nothing
Trying:
    bobs_change(40)
Expecting:
    Sorry Bob, you don't have enough
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 23, in __main__
Failed example:
    bobs_change(40)
Expected:
    Sorry Bob, you don't have enough
Got:
    sorry Bob, you dont have enough
2 items had no tests:
    __main__.bobs_change
    __main__.run_tests
**********************************************************************
1 items had failures:
   4 of   4 in __main__
4 tests in 3 items.
0 passed and 4 failed.
***Test Failed*** 4 failures.
>>> ================================ RESTART ================================
>>> 
>>> run_tests()
Trying:
    bobs_change(80)
Expecting:
    30
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 17, in __main__
Failed example:
    bobs_change(80)
Expected:
    30
Got nothing
Trying:
    bobs_change(132)
Expecting:
    82
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 19, in __main__
Failed example:
    bobs_change(132)
Expected:
    82
Got nothing
Trying:
    bobs_change(50)
Expecting:
    0
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 21, in __main__
Failed example:
    bobs_change(50)
Expected:
    0
Got nothing
Trying:
    bobs_change(40)
Expecting:
    Sorry Bob, you don't have enough
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 23, in __main__
Failed example:
    bobs_change(40)
Expected:
    Sorry Bob, you don't have enough
Got:
    sorry Bob, you don't have enough
2 items had no tests:
    __main__.bobs_change
    __main__.run_tests
**********************************************************************
1 items had failures:
   4 of   4 in __main__
4 tests in 3 items.
0 passed and 4 failed.
***Test Failed*** 4 failures.
>>> run_tests()
Trying:
    bobs_change(80)
Expecting:
    30
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 17, in __main__
Failed example:
    bobs_change(80)
Expected:
    30
Got nothing
Trying:
    bobs_change(132)
Expecting:
    82
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 19, in __main__
Failed example:
    bobs_change(132)
Expected:
    82
Got nothing
Trying:
    bobs_change(50)
Expecting:
    0
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 21, in __main__
Failed example:
    bobs_change(50)
Expected:
    0
Got nothing
Trying:
    bobs_change(40)
Expecting:
    Sorry Bob, you don't have enough
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 23, in __main__
Failed example:
    bobs_change(40)
Expected:
    Sorry Bob, you don't have enough
Got:
    sorry Bob, you don't have enough
2 items had no tests:
    __main__.bobs_change
    __main__.run_tests
**********************************************************************
1 items had failures:
   4 of   4 in __main__
4 tests in 3 items.
0 passed and 4 failed.
***Test Failed*** 4 failures.
>>> ================================ RESTART ================================
>>> 
>>> run_tests()
Trying:
    bobs_change(80)
Expecting:
    30
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 17, in __main__
Failed example:
    bobs_change(80)
Exception raised:
    Traceback (most recent call last):
      File "C:\Python33\lib\doctest.py", line 1313, in __run
        compileflags, 1), test.globs)
      File "<doctest __main__[0]>", line 1, in <module>
        bobs_change(80)
      File "H:\computering\problems\p01.1\bobs_change.py", line 43, in bobs_change
        print(moeny - 50)
    NameError: global name 'moeny' is not defined
Trying:
    bobs_change(132)
Expecting:
    82
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 19, in __main__
Failed example:
    bobs_change(132)
Exception raised:
    Traceback (most recent call last):
      File "C:\Python33\lib\doctest.py", line 1313, in __run
        compileflags, 1), test.globs)
      File "<doctest __main__[1]>", line 1, in <module>
        bobs_change(132)
      File "H:\computering\problems\p01.1\bobs_change.py", line 43, in bobs_change
        print(moeny - 50)
    NameError: global name 'moeny' is not defined
Trying:
    bobs_change(50)
Expecting:
    0
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 21, in __main__
Failed example:
    bobs_change(50)
Expected:
    0
Got nothing
Trying:
    bobs_change(40)
Expecting:
    Sorry Bob, you don't have enough
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 23, in __main__
Failed example:
    bobs_change(40)
Expected:
    Sorry Bob, you don't have enough
Got:
    sorry Bob, you don't have enough
2 items had no tests:
    __main__.bobs_change
    __main__.run_tests
**********************************************************************
1 items had failures:
   4 of   4 in __main__
4 tests in 3 items.
0 passed and 4 failed.
***Test Failed*** 4 failures.
>>> ================================ RESTART ================================
>>> 
>>> run_tests()
Trying:
    bobs_change(80)
Expecting:
    30
ok
Trying:
    bobs_change(132)
Expecting:
    82
ok
Trying:
    bobs_change(50)
Expecting:
    0
**********************************************************************
File "H:\computering\problems\p01.1\bobs_change.py", line 21, in __main__
Failed example:
    bobs_change(50)
Expected:
    0
Got nothing
Trying:
    bobs_change(40)
Expecting:
    Sorry Bob, you don't have enough
ok
2 items had no tests:
    __main__.bobs_change
    __main__.run_tests
**********************************************************************
1 items had failures:
   1 of   4 in __main__
4 tests in 3 items.
3 passed and 1 failed.
***Test Failed*** 1 failures.
>>> ================================ RESTART ================================
>>> 
>>> run_tests()
Trying:
    bobs_change(80)
Expecting:
    30
ok
Trying:
    bobs_change(132)
Expecting:
    82
ok
Trying:
    bobs_change(50)
Expecting:
    0
ok
Trying:
    bobs_change(40)
Expecting:
    Sorry Bob, you don't have enough
ok
2 items had no tests:
    __main__.bobs_change
    __main__.run_tests
1 items passed all tests:
   4 tests in __main__
4 tests in 3 items.
4 passed and 0 failed.
Test passed.
>>> 
